services:
  app:
    build: .
    container_name: spotify-server
    ports:
      - "8080:8080"
    depends_on:
      - redis-stack
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spotify
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis-stack:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-stack