version: '3.8'
services:
  # Use this if you not want to use web-ui
  #  redis:
  #    image: redis:7.2
  #    container_name: redis
  #    ports:
  #      - "6379:6379"

  redis-stack:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
