version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_CLOUD_API_KEY: ${CLOUDINARY_CLOUD_API_KEY}
      CLOUDINARY_CLOUD_SECRET: ${CLOUDINARY_CLOUD_SECRET}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: spotify_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
